CREATE TABLE user_surgeries (
    id BIGINT NOT NULL AUTO_INCREMENT,

    created_at DATETIME(6) NOT NULL,

    surgery_type ENUM (
        'ANTERIOR_CERVICAL_DISCECTOMY_FUSION',
        'ANTERIOR_LUMBAR_INTERBODY_FUSION',
        'ARTIFICIAL_DISC_REPLACEMENT',
        'DECOMPRESSION_SURGERY',
        'DISC_NUCLEOPLASTY',
        'FACET_JOINT_FUSION',
        'FORAMINOTOMY',
        'KYPHOPLASTY',
        'LAMINECTOMY',
        'LATERAL_LUMBAR_INTERBODY_FUSION',
        'MICRODISCECTOMY',
        'OTHER',
        'POSTERIOR_CERVICAL_FUSION',
        'POSTERIOR_LUMBAR_INTERBODY_FUSION',
        'SPINAL_DEFORMITY_CORRECTION',
        'SPINAL_FUSION',
        'SPINAL_REVISION_SURGERY',
        'SPINAL_TUMOR_REMOVAL',
        'TRANSFORAMINAL_LUMBAR_INTERBODY_FUSION',
        'VERTEBROPLASTY'
    ) NOT NULL,

    user_id BIGINT NOT NULL,

    CONSTRAINT pk_user_surgeries PRIMARY KEY (id),
    CONSTRAINT fk_user_surgeries_user
        FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
