package com.fitspine.enums;

public enum InjuryType {
    HERNIATED_DISC,
    BULGING_DISC,
    SCIATICA,
    SPINAL_STENOSIS,
    DEGENERATIVE_DISC_DISEASE,
    ANNULAR_TEAR,
    FACET_JOINT_SYNDROME,
    SPONDYLOLISTHESIS,
    CERVICAL_RADICULOPATHY,
    THORACIC_DISC_HERNIATION,
    LUMBAR_RADICULOPATHY,
    DISC_EXTRUSION,
    DISC_SEQUESTRATION,
    SPINAL_FRACTURE,
    SPINAL_TUMOR,
    SPINAL_INFECTION,
    POST_SURGICAL_PAIN,
    NON_SPECIFIC_LOWER_BACK_PAIN,
    NON_SPECIFIC_NECK_PAIN,
    OTHER
}
