package com.fitspine.enums;

public enum SurgeryType {
    MICRODISCECTOMY,
    LAMINECTOMY,
    SPINAL_FUSION,
    ARTIFICIAL_DISC_REPLACEMENT,
    FORAMINOTOMY,
    FACET_JOINT_FUSION,
    VERTEBROPLASTY,
    KYPHOPLASTY,
    DISC_NUCLEOPLASTY,
    DECOMPRESSION_SURGERY,
    POSTERIOR_CERVICAL_FUSION,
    ANTERIOR_CERVICAL_DISCECTOMY_FUSION, // ACDF
    ANTERIOR_LUMBAR_INTERBODY_FUSION,    // ALIF
    LATERAL_LUMBAR_INTERBODY_FUSION,     // LLIF
    POSTERIOR_LUMBAR_INTERBODY_FUSION,   // PLIF
    TRANSFORAMINAL_LUMBAR_INTERBODY_FUSION, // TLIF
    SPINAL_TUMOR_REMOVAL,
    SPINAL_DEFORMITY_CORRECTION,
    SPINAL_REVISION_SURGERY,
    OTHER
}
